
import { Section } from './types';

export const SECTIONS: Section[] = [
  {
    id: 'A',
    category: 'CONSCIOUSNESS (Spiritual Fulfillment)',
    title: 'Energy',
    questions: [
      { text: 'I am using energetic self-perception and shift myself and others energetically.' },
      { text: 'I am inspired and motivated and easily inspire and motivate others.' },
      { text: 'I am creating from a place of flow, power, passion, divine desires, and purpose.' },
      { text: 'I am using anabolic energy to expand, fuel, heal, create positive long-term success.' },
      { text: 'I am aware of how catabolic energy works and have eliminated it from my life.' },
      { text: 'I am positively influencing myself and others and am creating an impact in the world.' },
      { text: 'I am experiencing an extremely fulfilling life and experience very little frustration, stress and anxiety, or depression.' },
    ],
  },
  {
    id: 'B',
    category: 'CONSCIOUSNESS (Spiritual Fulfillment)',
    title: 'Awareness',
    questions: [
      { text: 'I am aware of what my primary level of consciousness is daily.' },
      { text: 'I am using spiral dynamics awareness to operating from higher consciousness levels.' },
      { text: 'I am aware of my shadow archetypes and have fully integrated them into my identity.' },
      { text: 'I am using a hedonic calendar to create complete flow and focus during the day.' },
      { text: 'I am effortless executing and focused on being not doing, I speak the truth fearlessly.' },
      { text: 'I am resonating energetically at a level 6 or 7 for the majority of the day.' },
      { text: 'I am quickly manifest and experience new realities in my life from the quantum field of oneness.' },
    ],
  },
  {
    id: 'C',
    category: 'CONNECTION (Relationships)',
    title: 'Love',
    questions: [
      { text: 'I am growing together instead of drifting apart from people in my life.' },
      { text: 'I am in control of my emotions and feel pure love for myself and others daily.' },
      { text: 'I am manifesting new and exciting relationships experiences.' },
      { text: 'I am communicating my divine love and accept others for who they are.' },
      { text: 'I am fully supported by my family and friends in challenging situations.' },
      { text: 'I am using a joint identity matrix to build a strong and positive family environment.' },
      { text: 'I am in no compromise relationships in my life and I do not judge others.' },
    ],
  },
  {
    id: 'D',
    category: 'CONNECTION (Relationships)',
    title: 'Tribe',
    questions: [
      { text: 'I am co-creating with others who are fully aligned with my mission and calling.' },
      { text: 'I am able to communicate my beliefs and mission to others and fearlessly ask for help.' },
      { text: 'I am regularly participating in groups that align with my passion and purpose.' },
      { text: 'I am easily attracting new people/clients and opportunities in my life.' },
      { text: 'I am confident that the seven closest people in my life have my back.' },
      { text: 'I am very comfortable in conflict with others and am not afraid to speak up.' },
      { text: 'I am creating new people daily who add to the quality of my life.' },
    ],
  },
  {
    id: 'E',
    category: 'CONTRIBUTION (Business & Career)',
    title: 'Career',
    questions: [
      { text: 'I am someone who jumps out of bed in the morning am excited to start my day.' },
      { text: 'I am alive and awakened in my professional life and people know it.' },
      { text: 'I am doing what I\'d be doing if I had a billion dollars in the bank.' },
      { text: 'I am working on a mission bigger than me that I believe in.' },
      { text: 'I am using intuition to make split-second decisions and living each day on purpose.' },
      { text: 'I am living each day in my purpose and have daily habits that support my dreams.' },
      { text: 'I am taking action on goals that are inspiring and I operate in my unique abilities.' },
    ],
  },
  {
    id: 'F',
    category: 'CONTRIBUTION (Business & Career)',
    title: 'Abundance',
    questions: [
      { text: 'I am honoring my highest values in the work I do in the world.' },
      { text: 'I am being abundantly compensated and making what I desire.' },
      { text: 'I am effortlessly creating, new clients, new business and career opportunities.' },
      { text: 'I am articulating my mission in a way that people understand and see value in.' },
      { text: 'I am sharing my vision passionately with others daily.' },
      { text: 'I am providing a 10x value in the lives of my clients and inside of the organization.' },
      { text: 'I am easily and graciously receiving money and support from others.' },
    ],
  },
  {
    id: 'G',
    category: 'COMMITMENT (Health & Fitness)',
    title: 'Fitness',
    questions: [
      { text: 'I am in the best shape of my life and have no physical limitations.' },
      { text: 'I am energized throughout the day, stay able to stay focused and present.' },
      { text: 'I am powerful, strong and make healthy choices. I sleep for 8 hours and meditate.' },
      { text: 'I am able to do 50 consecutive pushups and run a mile.' },
      { text: 'I am taking breaks during work hours for 15-20 minutes for physical activity.' },
      { text: 'I am exercising 2-5 times a week for a minimum of 30-60 minutes.' },
      { text: 'I am starting my day with morning movement and have workout routines.' },
    ],
  },
  {
    id: 'H',
    category: 'COMMITMENT (Health & Fitness)',
    title: 'Health',
    questions: [
      { text: 'I am eating healthy foods that are adding to my energy instead of it taking away.' },
      { text: 'I am taking vitamins daily to supplement my daily diet.' },
      { text: 'I am eating three meals a day and drink 32oz of water first thing in the morning.' },
      { text: 'I am burning just as many calories as I am taking in daily.' },
      { text: 'I am doing some sort of light activity before meals.' },
      { text: 'I am not going out to restaurants that serve large portions and unhealthy foods.' },
      { text: 'I am daily or occasionally fasting and cleansing my body.' },
    ],
  },
  {
    id: 'I',
    category: 'ADVENTURE (Life Experiences)',
    title: 'Adventure (Challenge)',
    questions: [
      { text: 'I am challenging myself to protect my first 90 min. and complete most important tasks.' },
      { text: 'I am challenging myself to fearlessly express gratitude and love to others.' },
      { text: 'I am challenging myself to live my ideal day and follow a schedule that honors my life.' },
      { text: 'I am challenging myself to do one thing a day that scares me.' },
      { text: 'I am challenging myself each day to take immediate action on the things I desire.' },
      { text: 'I am challenging myself to say yes to that which serves me and no to all else.' },
      { text: 'I am challenging myself at least 4% outside of my comfort zone daily.' },
    ],
  },
  {
    id: 'J',
    category: 'ADVENTURE (Life Experiences)',
    title: 'Adventure (Connection)',
    questions: [
      { text: 'I am investing time outdoors in nature to reconnect with myself and body.' },
      { text: 'I am feeling there is more than enough time in the day, time often stands still.' },
      { text: 'I am investing time in travel at least 4 times a year and experiencing new adventures.' },
      { text: 'I am checking off my bucket list items at least once a month.' },
      { text: 'I am spending less than 8 hours a day behind a computer or phone screen.' },
      { text: 'I am enjoying at least 1-2 hobbies and investing quality time with family.' },
      { text: 'I am investing time with those I love and regularly journal my thoughts around these experiences.' },
    ],
  },
];

export const CORPORATE_SECTIONS: Section[] = [
  {
    id: 'A',
    category: 'CONSCIOUSNESS (Energy & Awareness)',
    title: 'Energy',
    questions: [
      { text: 'Our employees are using energetic self-perception to lead energetically.' },
      { text: 'Our employees are inspired and motivated and easily inspire and motivate others.' },
      { text: 'Our employees create from a place of flow, power, passion, desires, and purpose.' },
      { text: 'Our employees are using anabolic energy to create positive long-term success.' },
      { text: 'Our employees are aware of how catabolic energy disrupts healthy company culture.' },
      { text: 'Our employees are positively influencing others and creating an impact in the world.' },
      { text: 'Our employees are experiencing an extremely fulfilling career and experience very little frustration, stress, and anxiety, or depression.' },
    ],
  },
  {
    id: 'B',
    category: 'CONSCIOUSNESS (Energy & Awareness)',
    title: 'Awareness',
    questions: [
      { text: 'Our employees are aware of what their primary level of consciousness is daily.' },
      { text: 'Our employees use spiral dynamics to operate from in higher consciousness.' },
      { text: 'Our employees are aware of their shadow archetypes and how they impact others.' },
      { text: 'Our employees are using a hedonic calendar to create complete flow and focus during the day.' },
      { text: 'Our employees are effortlessly executing and speak truth fearlessly.' },
      { text: 'Our employees are resonating energetically at a positive level for the majority of the day.' },
      { text: 'Our employees quickly manifest new opportunities.' },
    ],
  },
  {
    id: 'C',
    category: 'CONNECTION (Culture & Tribe)',
    title: 'Culture',
    questions: [
      { text: 'Our employees are growing together instead of drifting apart as a result of stress.' },
      { text: 'Our employees are in control of their emotions and feel love for themselves and others daily.' },
      { text: 'Our employees are experiencing new and exciting relationships at work.' },
      { text: 'Our employees are communicating love, appreciation and acceptance of each other.' },
      { text: 'Our employees feel fully supported by team members when in challenging situations.' },
      { text: 'Our employees are using a joint identity matrix to build strong relationships at work.' },
      { text: 'Our employees are in no compromise relationships and do not judge others.' },
    ],
  },
  {
    id: 'D',
    category: 'CONNECTION (Culture & Tribe)',
    title: 'Tribe',
    questions: [
      { text: 'Our employees are co-creating and fully aligned with our mission.' },
      { text: 'Our employees are able to fearlessly ask for help and support from leadership teams.' },
      { text: 'Our employees regularly participate in groups that align with their passion and purpose.' },
      { text: 'Our employees are easily attracting new people/clients into the business.' },
      { text: 'Our employees are confident their team members have their back.' },
      { text: 'Our employees are very comfortable in conflict are not afraid to speak up.' },
      { text: 'Our employees are recruiting new people daily who add to the quality of our culture and impact in the world.' },
    ],
  },
  {
    id: 'E',
    category: 'CONTRIBUTION (Engagement & Performance)',
    title: 'Engagement',
    questions: [
      { text: 'Our employees jump out of bed in the morning and are excited to start their day.' },
      { text: 'Our employees raving fans of our company and our clients know it.' },
      { text: 'Our employees are doing what they’d be doing if they had a billion dollars in the bank.' },
      { text: 'Our employees are working on a mission bigger than themselves, and that they believe in.' },
      { text: 'Our employees are using intuition to make split-second decisions and live each day on purpose.' },
      { text: 'Our employees have daily habits that support their dreams.' },
      { text: 'Our employees are operating in their unique abilities and taking action on personal goals that inspire them.' },
    ],
  },
  {
    id: 'F',
    category: 'CONTRIBUTION (Engagement & Performance)',
    title: 'Performance',
    questions: [
      { text: 'Our employees are honoring their highest values in the work they do.' },
      { text: 'Our employees are being abundantly compensated and making what they desire.' },
      { text: 'Our employees are effortlessly creating new clients, new business, and career opportunities.' },
      { text: 'Our employees are articulating their mission in a way that people understand and see value in.' },
      { text: 'Our employees are sharing their vision passionately with others daily.' },
      { text: 'Our employees are providing a 10x value in the lives of our clients and inside of the organization.' },
      { text: 'Our employees are easily and graciously generating revenue and support.' },
    ],
  },
  {
    id: 'G',
    category: 'COMMITMENT (Health & Wellness)',
    title: 'Wellness',
    questions: [
      { text: 'Our employees are in the best shape of their life and have no physical limitations.' },
      { text: 'Our employees are energized throughout the day, and able to stay focused and present.' },
      { text: 'Our employees are powerful, strong, and make healthy choices. They sleep for 8 hours and meditate.' },
      { text: 'Our employees are able to do at least 25-50 pushups and run a mile.' },
      { text: 'Our employees are taking breaks during work hours for 15-20 minutes for physical activity.' },
      { text: 'Our employees are exercising 2-5 times a week for a minimum of 30-60 minutes.' },
      { text: 'Our employees are starting their day with morning movement and have workout routines.' },
    ],
  },
  {
    id: 'H',
    category: 'COMMITMENT (Health & Wellness)',
    title: 'Health',
    questions: [
      { text: 'Our employees are eating healthy foods that are adding to their energy instead of it taking away.' },
      { text: 'Our employees are taking vitamins daily to supplement their daily diet.' },
      { text: 'Our employees are eating three meals a day and drink 32oz of water first thing in the morning' },
      { text: 'Our employees are burning just as many calories as they are taking in daily.' },
      { text: 'Our employees are doing some sort of light activity before meals.' },
      { text: 'Our employees are not going out to restaurants that serve large portions and unhealthy foods.' },
      { text: 'Our employees are daily or occasionally fasting and cleansing their body.' },
    ],
  },
  {
    id: 'I',
    category: 'ADVENTURE (Team Building Experiences)',
    title: 'Adventure (Challenge)',
    questions: [
      { text: 'Our employees are challenging themselves to protect their first 90 min and complete their most important tasks first.' },
      { text: 'Our employees are challenging themselves to fearlessly express gratitude and love to others.' },
      { text: 'Our employees are challenging themselves to live their ideal day and follow a schedule that honors their life.' },
      { text: 'Our employees are challenging themselves to do one thing a day that scares me.' },
      { text: 'Our employees are challenging themselves daily to take immediate action on the things they desire.' },
      { text: 'Our employees are challenging themselves to say yes to that which serves them and no to all else.' },
      { text: 'Our employees are challenging themselves at least 4% outside of their comfort zone daily.' },
    ],
  },
  {
    id: 'J',
    category: 'ADVENTURE (Team Building Experiences)',
    title: 'Adventure (Connection)',
    questions: [
      { text: 'Our employees are investing time outdoors in nature to reconnect with each other.' },
      { text: 'Our employees feel there is enough time in the day, time often stands still.' },
      { text: 'Our employees are investing time in travel at least 4 times a year.' },
      { text: 'Our employees are checking off bucket list items at least once a month.' },
      { text: 'Our employees are spending less than 8 hours a day behind a computer or phone screen.' },
      { text: 'Our employees enjoy at least 1-2 external hobbies they enjoy.' },
      { text: 'Our employees are investing in quality time with loved ones regularly.' },
    ],
  },
];
