
import { Section } from './types';

export const SECTIONS: Section[] = [
  {
    id: 'A',
    category: 'CONSCIOUSNESS (Spiritual Fulfillment)',
    title: 'Energy',
    questions: [
      { text: 'I am using energetic self-perception and shift myself and others energetically.' },
      { text: 'I am inspired and motivated and easily inspire and motivate others.' },
      { text: 'I am creating from a place of flow, power, passion, divine desires, and purpose.' },
      { text: 'I am using anabolic energy to expand, fuel, heal, create positive long-term success.' },
      { text: 'I am aware of how catabolic energy works and have eliminated it from my life.' },
      { text: 'I am positively influencing myself and others and am creating an impact in the world.' },
      { text: 'I am experiencing an extremely fulfilling life and experience very little frustration, stress and anxiety, or depression.' },
    ],
  },
  {
    id: 'B',
    category: 'CONSCIOUSNESS (Spiritual Fulfillment)',
    title: 'Awareness',
    questions: [
      { text: 'I am aware of what my primary level of consciousness is daily.' },
      { text: 'I am using spiral dynamics awareness to operating from higher consciousness levels.' },
      { text: 'I am aware of my shadow archetypes and have fully integrated them into my identity.' },
      { text: 'I am using a hedonic calendar to create complete flow and focus during the day.' },
      { text: 'I am effortless executing and focused on being not doing, I speak the truth fearlessly.' },
      { text: 'I am resonating energetically at a level 6 or 7 for the majority of the day.' },
      { text: 'I am quickly manifest and experience new realities in my life from the quantum field of oneness.' },
    ],
  },
  {
    id: 'C',
    category: 'CONNECTION (Relationships)',
    title: 'Love',
    questions: [
      { text: 'I am growing together instead of drifting apart from people in my life.' },
      { text: 'I am in control of my emotions and feel pure love for myself and others daily.' },
      { text: 'I am manifesting new and exciting relationships experiences.' },
      { text: 'I am communicating my divine love and accept others for who they are.' },
      { text: 'I am fully supported by my family and friends in challenging situations.' },
      { text: 'I am using a joint identity matrix to build a strong and positive family environment.' },
      { text: 'I am in no compromise relationships in my life and I do not judge others.' },
    ],
  },
  {
    id: 'D',
    category: 'CONNECTION (Relationships)',
    title: 'Tribe',
    questions: [
      { text: 'I am co-creating with others who are fully aligned with my mission and calling.' },
      { text: 'I am able to communicate my beliefs and mission to others and fearlessly ask for help.' },
      { text: 'I am regularly participating in groups that align with my passion and purpose.' },
      { text: 'I am easily attracting new people/clients and opportunities in my life.' },
      { text: 'I am confident that the seven closest people in my life have my back.' },
      { text: 'I am very comfortable in conflict with others and am not afraid to speak up.' },
      { text: 'I am creating new people daily who add to the quality of my life.' },
    ],
  },
  {
    id: 'E',
    category: 'CONTRIBUTION (Business & Career)',
    title: 'Career',
    questions: [
      { text: 'I am someone who jumps out of bed in the morning am excited to start my day.' },
      { text: 'I am alive and awakened in my professional life and people know it.' },
      { text: 'I am doing what I\'d be doing if I had a billion dollars in the bank.' },
      { text: 'I am working on a mission bigger than me that I believe in.' },
      { text: 'I am using intuition to make split-second decisions and living each day on purpose.' },
      { text: 'I am living each day in my purpose and have daily habits that support my dreams.' },
      { text: 'I am taking action on goals that are inspiring and I operate in my unique abilities.' },
    ],
  },
  {
    id: 'F',
    category: 'CONTRIBUTION (Business & Career)',
    title: 'Abundance',
    questions: [
      { text: 'I am honoring my highest values in the work I do in the world.' },
      { text: 'I am being abundantly compensated and making what I desire.' },
      { text: 'I am effortlessly creating, new clients, new business and career opportunities.' },
      { text: 'I am articulating my mission in a way that people understand and see value in.' },
      { text: 'I am sharing my vision passionately with others daily.' },
      { text: 'I am providing a 10x value in the lives of my clients and inside of my organization.' },
      { text: 'I am easily and graciously receiving money and support from others.' },
    ],
  },
  {
    id: 'G',
    category: 'COMMITMENT (Health & Fitness)',
    title: 'Fitness',
    questions: [
      { text: 'I am in the best shape of my life and have no physical limitations.' },
      { text: 'I am energized throughout the day, stay able to stay focused and present.' },
      { text: 'I am powerful, strong and make healthy choices. I sleep for 8 hours and meditate.' },
      { text: 'I am able to do 50 consecutive pushups and run a mile.' },
      { text: 'I am taking breaks during work hours for 15-20 minutes for physical activity.' },
      { text: 'I am exercising 2-5 times a week for a minimum of 30-60 minutes.' },
      { text: 'I am starting my day with morning movement and have workout routines.' },
    ],
  },
  {
    id: 'H',
    category: 'COMMITMENT (Health & Fitness)',
    title: 'Health',
    questions: [
      { text: 'I am eating healthy foods that are adding to my energy instead of it taking away.' },
      { text: 'I am taking vitamins daily to supplement my daily diet.' },
      { text: 'I am eating three meals a day and drink 32oz of water first thing in the morning.' },
      { text: 'I am burning just as many calories as I am taking in daily.' },
      { text: 'I am doing some sort of light activity before meals.' },
      { text: 'I am not going out to restaurants that serve large portions and unhealthy foods.' },
      { text: 'I am daily or occasionally fasting and cleansing my body.' },
    ],
  },
  {
    id: 'I',
    category: 'ADVENTURE (Life Experiences)',
    title: 'Adventure (Challenge)',
    questions: [
      { text: 'I am challenging myself to protect my first 90 min. and complete most important tasks.' },
      { text: 'I am challenging myself to fearlessly express gratitude and love to others.' },
      { text: 'I am challenging myself to live my ideal day and follow a schedule that honors my life.' },
      { text: 'I am challenging myself to do one thing a day that scares me.' },
      { text: 'I am challenging myself each day to take immediate action on the things I desire.' },
      { text: 'I am challenging myself to say yes to that which serves me and no to all else.' },
      { text: 'I am challenging myself at least 4% outside of my comfort zone daily.' },
    ],
  },
  {
    id: 'J',
    category: 'ADVENTURE (Life Experiences)',
    title: 'Adventure (Connection)',
    questions: [
      { text: 'I am investing time outdoors in nature to reconnect with myself and body.' },
      { text: 'I am feeling there is more than enough time in the day, time often stands still.' },
      { text: 'I am investing time in travel at least 4 times a year and experiencing new adventures.' },
      { text: 'I am checking off my bucket list items at least once a month.' },
      { text: 'I am spending less than 8 hours a day behind a computer or phone screen.' },
      { text: 'I am enjoying at least 1-2 hobbies and investing quality time with family.' },
      { text: 'I am investing time with those I love and regularly journal my thoughts around these experiences.' },
    ],
  },
];
